name: Continuos Integration aws sam

on:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    name: test app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install flake8
          if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          flake8 . --count --show-source --statistics
      - name: Test with pytest
        run: |
          python3 -m unittest tests/test.py
  deploy:
    name: deploy
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: install flake8
        env:
          TEST_KEY: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$TEST_KEY"

