name: Continuos Integration aws sam

on:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    name: testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install flake8
          if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          flake8 . --count --show-source --statistics
      - name: Test with code
        env:
          ENV: ${{ secrets.ENV }}
          DB_HOST: '${{ secrets.DB_HOST }}'
          DB_PORT: '${{ secrets.DB_PORT }}'
          DB_USER: '${{ secrets.DB_USER }}'
          DB_PASS: '${{ secrets.DB_PASS }}'
          DB_NAME: '${{ secrets.DB_NAME }}'
        run: |
          env
          python3 -m unittest tests/test.py
  deploy:
    name: deploy
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: install flake8
        env:
          TEST_KEY: '${{ secrets.GITHUB_TOKEN }}'
        run: |
          echo "$TEST_KEY"

